sonar.projectKey=josephrojas_devops_challenge_python
sonar.organization=joseph-rojas-prv


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=devops_challenge_python
sonar.projectVersion=1.0

sonar.modules=dictionary,spending_calculator,nth_letter


dictionary.sonar.projectName=Dictionary
dictionary.sonar.projectBaseDir=exercise/dictionary
dictionary.sonar.sources=src
dictionary.sonar.tests=tests
dictionary.sonar.python.coverage.reportPaths=coverage.xml
dictionary.sonar.python.version=3.12

spending_calculator.sonar.projectName=Spending_Calculator
spending_calculator.sonar.projectBaseDir=exercise/spending_calculator
spending_calculator.sonar.sources=src
spending_calculator.sonar.tests=tests
spending_calculator.sonar.python.coverage.reportPaths=coverage.xml
spending_calculator.sonar.python.version=3.12

nth_letter.sonar.projectName=Nth_letter
nth_letter.sonar.projectBaseDir=exercise/nth_letter
nth_letter.sonar.sources=src
nth_letter.sonar.tests=tests
nth_letter.sonar.python.coverage.reportPaths=coverage.xml
nth_letter.sonar.python.version=3.12

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8spending_calculator